### ISSUE TITLE
"openstack-snapshoter" requires jq

### ISSUE THREAD

**Issue by joshmoore** [openmicroscopy/infrastructure#139]
This may could/should be encapsulated in a role.

**Comment by joshmoore** [comment]
```
(ebi) (ebi) [jamoore@orca-4 scripts]$ bash os-idr-mkvol.sh
os-idr-mkvol.sh: line 5: jq: command not found
[Errno 32] Broken pipe
os-idr-mkvol.sh: line 16: jq: command not found
^CTraceback (most recent call last):
  File "/lifesci/groups/jrs/jamoore/miniconda2/bin/openstack", line 7, in <module>
    from openstackclient.shell import main
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/openstackclient/shell.py", line 33, in <module>
    from openstackclient.common import clientmanager
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/openstackclient/common/clientmanager.py", line 27, in <module>
    from openstackclient.api import auth
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/openstackclient/api/auth.py", line 21, in <module>

(ebi) (ebi) [jamoore@orca-4 scripts]$     from keystoneclient.auth import base
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/keystoneclient/auth/__init__.py", line 16, in <module>
    from keystoneclient.auth.conf import *  # noqa
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/keystoneclient/auth/conf.py", line 14, in <module>
    from oslo_config import cfg
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/oslo_config/cfg.py", line 380, in <module>
    from oslo_config import types
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/oslo_config/types.py", line 27, in <module>
    import netaddr
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/netaddr/__init__.py", line 18, in <module>
    from netaddr.core import (AddrConversionError, AddrFormatError,
  File "/lifesci/groups/jrs/jamoore/miniconda2/lib/python2.7/site-packages/netaddr/core.py", line 6, in <module>
    """Common code shared between various netaddr sub modules"""
KeyboardInterrupt
```
